# Generated by Django 4.0.6 on 2022-08-08 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_active',
        ),
    ]
